---
title: Cindy Cournoyer
email: cindy@dulcedo.com
quote: I want to take good photos, drink coffee and travel the world.
instafeed:
  clientid: ''
  userid: 279336649
  token: 279336649.8c9a4c5.2c37584b3f064328b9299bc1cd050773
  homecount: 8
  sidecount: 4
