---
upload_path: "/assets/img/"
frontmatter_file_url_template: "/assets/img/"
body_file_url_template: "/assets/img/"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
